version: '3.8'

services:
  # 🆕 НОВЫЙ СЕРВИС ДЛЯ ФРОНТЕНДА
  frontend:
    container_name: raffle-frontend
    build:
      context: ./client # ❗️ Указываем путь к папке с фронтендом
      dockerfile: Dockerfile
    ports:
      - '5173:80' # Пробрасываем порт 80 контейнера на порт 3000 на вашем ПК
    restart: unless-stopped
    depends_on:
      - backend # Запускаем фронтенд после бэкенда

  # 1. Сервис базы данных PostgreSQL (почти без изменений)
  db:
    image: postgres:15-alpine
    container_name: raffle-db
    env_file:
      - ./server/.env 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 2. Сервис для применения миграций
  migrate:
    image: migrate/migrate
    container_name: raffle-migrate
    volumes:
      - ./server/migrations:/migrations # ❗️ ИЗМЕНЕНО: Указываем правильный путь к миграциям
    command:
      [
        '-path',
        '/migrations',
        '-database',
        'postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable',
        'up',
      ]
    depends_on:
      db:
        condition: service_healthy
    restart: 'no'

  # 3. Сервис вашего Go-бэкенда
  backend:
    container_name: raffle-backend
    build: ./server 
    env_file:
      - ./server/.env 
    environment:
      - DB_HOST=db
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  postgres_data:
